name: Coding Style Check

on:
  push:
    branches: ["ga-ignore-*"]
  pull_request:
    branches: ["ga-ignore-*"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!
