name: Coding Style Check

on:
  push:
    branches: ["ga-ignore-*"]
  pull_request:
    branches: ["ga-ignore-*"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: check.sh $(pwd) $(pwd)
