name: Coding Style Check

env:
  MIRROR_URL: "git@github.com:EpitechPGEPromo2029/B-DOP-200-TLS-2-1-chocolatine-suleyman.laarabi.git"
  EXECUTABLES: ""
on:
  push:
    branches-ignore: ["ga-ignore-*"]
  pull_request:
    branches-ignore: ["ga-ignore-*"]

  workflow_dispatch:

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run coding style checker
        run: check.sh $(pwd) $(pwd)
      - name: Show coding style errors
        run: |
          if [ -s coding-style-reports.log ]; then
            while IFS= read -r line; do
              path=$(echo "$line" | cut -d ':' -f1 | sed 's|^\./||')
              line_num=$(echo "$line" | cut -d ':' -f2)
              type=$(echo "$line" | cut -d ':' -f3 | cut -d ':' -f1 | cut -d '-' -f1)
              code=$(echo "$line" | cut -d ':' -f3 | cut -d ':' -f1)
              echo "::error file=$path,line=$line_num::$type coding style error: $path#L$line_num $code"
            done < coding-style-reports.log
            exit 1
          fi

  push_to_mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
